version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres